import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import { getUser, logout } from "@/lib/auth";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user = await getUser();
  // if(!user) redirect("/")

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full">
          <Navbar user={user} logout={logout} />
        </header>
        {children}
      </body>
    </html>
  );
}
