import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper dark:bg-black dark:text-white">
          <header className="w-full">
            <Navbar>
            <li className="w-24 hover:text-white hover:bg-orange-700 py-2 pl-4 dark:text-orange-200">
                      <a href="/">Home</a>
                  </li>
                  <li className="w-24 hover:text-white hover:bg-orange-700 py-2 pl-4 dark:text-orange-200">
                      <a href="/about">About</a>
                  </li>
                  <li className="w-24 hover:text-white hover:bg-orange-700 py-2 pl-4 dark:text-orange-200">
                      <a href="/events">Events</a>
                  </li>
                  <li className="w-24 hover:text-white hover:bg-orange-700 py-2 pl-4 dark:text-orange-200">
                      <a href="/contact">Contact</a>
                  </li>
            </Navbar>
          </header>
          {children}
          <Footer></Footer>
        </div>      
      </body>
    </html>
  );
}
